In [3]:
import numpy as np
char_arr=np.array(['a','b','c'])
char_arr

array(['a', 'b', 'c'], dtype='<U1')

In [4]:
ch_arr2=np.array(["supervised","unsupervised","sEMi-supervised","reinforcement"])
low_arr=np.char.lower(ch_arr2)
low_arr

array(['supervised', 'unsupervised', 'semi-supervised', 'reinforcement'],
      dtype='<U15')

In [5]:
cleaned_arr=np.char.replace(low_arr,"-"," ")
cleaned_arr


array(['supervised', 'unsupervised', 'semi supervised', 'reinforcement'],
      dtype='<U15')

In [6]:
array1=np.array([1,2,3,4])
array1

array([1, 2, 3, 4])

In [7]:
array1.dtype

dtype('int32')

In [8]:
low_arr.dtype

dtype('<U15')

In [9]:
array8=np.array([1,2,3,4,5],dtype='S')

In [10]:
array8

array([b'1', b'2', b'3', b'4', b'5'], dtype='|S1')

In [11]:
array8=np.array([1,2,3,4,5],dtype='F')

In [12]:
array8

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j], dtype=complex64)

In [13]:
array8=np.array([1,2,3,4,5],dtype='float64')
array8
array8.dtype

dtype('float64')

In [14]:
array2conv=array8.astype('f')
array2conv

array([1., 2., 3., 4., 5.], dtype=float32)

In [15]:
array7conv=array2conv.astype('i')
array7conv

array([1, 2, 3, 4, 5], dtype=int32)

In [16]:
char_conv=char_arr.astype('i')
char_conv

ValueError: invalid literal for int() with base 10: 'a'

In [17]:
ars1=np.ones(3)
ars1

array([1., 1., 1.])

In [18]:
ars2=np.zeros(3)
ars2

array([0., 0., 0.])

In [19]:
ars3=np.random.random(3)
ars3

array([0.06215666, 0.81157141, 0.99875315])

In [21]:
numone=np.ones((2,2),dtype=int)
numone

array([[1, 1],
       [1, 1]])

In [22]:
numsone=np.ones((3,2))
numsone

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
dimones=np.ones((4,3,2))
dimones.ndim

3

In [24]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[5,6,7],[8,9,10]])
addition=arr1+arr2
print("addition:\n",addition)

addition:
 [[ 6  8 10]
 [12 14 16]]


In [25]:
subtraction=arr1-arr2
print("subtraction:\n",subtraction)

subtraction:
 [[-4 -4 -4]
 [-4 -4 -4]]


In [26]:
multiplication=arr1*arr2

In [27]:
print("multiplication",multiplication)

multiplication [[ 5 12 21]
 [32 45 60]]


In [28]:
division=arr1/arr2
print("division",division)

division [[0.2        0.33333333 0.42857143]
 [0.5        0.55555556 0.6       ]]


In [29]:
power=np.power(arr1,arr2)
print("power:\n",power)

power:
 [[       1       64     2187]
 [   65536  1953125 60466176]]


In [31]:
array2d=np.array([[1,2,3],[4,5,6]])
array1d=np.array([10,20,22])
result=array2d+array1d
result

array([[11, 22, 25],
       [14, 25, 28]])

In [32]:
range_array=np.arange(0,10,3)
range_array

array([0, 3, 6, 9])

In [34]:
a=np.random.randint(low=1,size=2)
a

array([0, 0])

In [35]:
b=np.random.randint(low=1,high=6,size=(2,3))
b

array([[3, 1, 4],
       [1, 1, 3]])

In [36]:
np.concatenate([arr1+arr2])

array([[ 6,  8, 10],
       [12, 14, 16]])

In [37]:
flatarr=arr1.flatten()
flatarr

array([1, 2, 3, 4, 5, 6])

In [38]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [39]:
np.info(np.ndarray.ndim)

Number of array dimensions.

Examples
--------
>>> x = np.array([1, 2, 3])
>>> x.ndim
1
>>> y = np.zeros((2, 3, 4))
>>> y.ndim
3
